### ISSUE TITLE
Got IncompleteBody error, when pull a big image which is 1.93G.

### ISSUE THREAD

**Issue by BaoshunFang** [confidential-containers/image-rs#145]
My container image is 1.93 Gbytes, when using kata-agent to pull image, it always failed with below error:

May 10 07:52:03 k8s-master containerd[1153]: time="2023-05-10T07:52:03.418712368Z" level=info msg="PullImage \"docker.io/test/test:latest\""
May 10 07:52:03 k8s-master containerd[1153]: time="2023-05-10T07:52:03.418798917Z" level=info msg="TaskManager get ImageService succeed." id=45399c080ecae7bf8800aae9509e960061d0bf3bdfece9b57d7daa95b86f4f4c
May 10 07:54:38 k8s-master containerd[1153]: time="2023-05-10T07:54:38.754185654Z" level=error msg="agent pull image err. rpc error: code = Internal desc = failed to handle layer: hasher sha256 : channel: read failed Custom { kind: Other, error: reqwest::Error { kind: Body, source: hyper::Error(Body, Custom { kind: UnexpectedEof, error: IncompleteBody }) } }" name=containerd-shim-v2 pid=375818 sandbox=45399c080ecae7bf8800aae9509e960061d0bf3bdfece9b57d7daa95b86f4f4c source=virtcontainers subsystem=kata_agent
May 10 07:54:38 k8s-master containerd[1153]: time="2023-05-10T07:54:38.754316393Z" level=error msg="kata runtime PullImage err. rpc error: code = Internal desc = failed to handle layer: hasher sha256 : channel: read failed Custom { kind: Other, error: reqwest::Error { kind: Body, source: hyper::Error(Body, Custom { kind: UnexpectedEof, error: IncompleteBody }) } }" name=containerd-shim-v2 pid=375818 sandbox=45399c080ecae7bf8800aae9509e960061d0bf3bdfece9b57d7daa95b86f4f4c source=containerd-kata-shim-v2
May 10 07:54:38 k8s-master containerd[1153]: time="2023-05-10T07:54:38.754529642Z" level=error msg="PullImage \"docker.io/test/test:latest\" failed" error="rpc error: code = Internal desc = failed to handle layer: hasher sha256 : channel: read failed Custom { kind: Other, error: reqwest::Error { kind: Body, source: hyper::Error(Body, Custom { kind: UnexpectedEof, error: IncompleteBody }) } }"

**Comment by fitzthum** [comment]
You might try increasing guest memory size. You can do this by increasing the `default_memory` value in the Kata Config file (or via annotation).

**Comment by BaoshunFang** [comment]
> You might try increasing guest memory size. You can do this by increasing the `default_memory` value in the Kata Config file (or via annotation).

The `default_memory` value is already 40960， but the error still comes up occasionally.

**Comment by arronwy** [comment]
Hi @BaoshunFang , can you try with the unit test of `image-rs`  https://github.com/confidential-containers/image-rs/blob/main/src/pull.rs#L415 with your image?

We tested async pull withs more than 10G container image with local registry, I not sure whether it is due to network issue with docker.io, BTW can you share the docker image address, we can also have a try.

**Comment by BaoshunFang** [comment]
@arronwy The address is `docker.io/pawsonfang/lanxiang_image`

**Comment by arronwy** [comment]
> @arronwy The address is `docker.io/pawsonfang/lanxiang_image`

I tried with this image from local registry:
test pull::tests::test_async_pull_client has been running for over 60 seconds
test pull::tests::test_async_pull_client ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 62 filtered out; finished in 120.01s

I also found the image has 17 layers, how may CPU resource is allocated for the pod? by default `image-rs` will spawn a thread for each layer, maybe we need restrict to limited thread with small pod CPU spec :
```
Copying blob 99803d4b97f3 done
Copying blob 4c9bae0d4570 done
Copying blob 1f08725a9e49 done
Copying blob 19d220c9f262 done
Copying blob 9d5922ac4adf done
Copying blob c2f8811429d9 done
Copying blob abbd3719feb2 done
Copying blob 95a3adea7a06 done
Copying blob e77d06d780ea done
Copying blob 94f1668f4e11 done
Copying blob cfef385de975 done
Copying blob 2e386aa34a5d done
Copying blob 00f66349bbc1 done
Copying blob ee646cd4ac92 done
Copying blob 984e27116077 done
Copying blob 33d5e26eb058 done
Copying blob 8ca7e297b771 done
Copying config 5b1528f044 done
```

**Comment by BaoshunFang** [comment]
how may CPU resource is allocated for the pod?
--------------------------
`deault_vcpus = 1`
`default_memory = 40960`

**Comment by fitzthum** [comment]
@arronwy I have run into very similar issues where container image pulling fails when the guest doesn't have enough vCPUs. It would be good if we could avoid this or somehow provide a clearer error message.

**Comment by arronwy** [comment]
Hi @BaoshunFang @fitzthum  Can you help verify whether this PR can fix your issue: https://github.com/confidential-containers/image-rs/pull/146

I verify it with my local registry which can improve the performance for pod with only 1 CPU, but I can not reproduce the error you meet:
Without max concurrent download limit:
```
  Normal  Pulling    18s   kubelet            Pulling image "registry.domain.local/lanxing_image"
  Normal  Pulled     1s    kubelet            Successfully pulled image "registry.domain.local/lanxing_image" in 17.29288467s (17.292891089s including waiting)
```
With max concurrent download limit:
```
  Normal  Pulling    20s   kubelet            Pulling image "registry.domain.local/lanxing_image"
  Normal  Pulled     5s    kubelet            Successfully pulled image "registry.domain.local/lanxing_image" in 15.642932324s (15.642938168s including waiting)
```
