### ISSUE TITLE
Different policy.json layout from containers/image

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/image-rs#40]
As containers/image [published new field](https://github.com/containers/image/commit/df1b3a7d24cb6c79e75e9fa0b87d6629414c0a9d#diff-206037061c400398fb3ac71cd19cd7cbbbec9288a8d00b29b7d867d265d34052) in `policy.json` to support `sigstoresign`(including cosign), this format is a little different from ours.

Theirs is like
```json
{
    "type":    "sigstoreSigned",
    "keyPath": "/path/to/local/keyring/file",
    "keyData": "base64-encoded-keyring-data",
    "signedIdentity": identity_requirement
}
```

And ours do not change `type` field when this Policy Requirement is a signing scheme. If cosign is supported by us, the format will be like

```json
{
    "type":    "signedBy",
    "scheme": "cosign",
    "keyPath": "/path/to/local/keyring/file",
    "keyData": "base64-encoded-keyring-data",
    "signedIdentity": identity_requirement
}
```

The `scheme` field is brought in https://github.com/confidential-containers/image-rs/pull/31. Because the `type` may include `insecureAcceptAnything` and `reject`, we introduced `scheme` field to show that "this policy is to verify signature, and the signing scheme is XXX" rather than extended `type`.

The question is whether we should modify our existing layout of Policy Requirement to follow the `containers/image`'s?
Our layout scheme is better for 
* More understandable and extensible for new signing schemes and Policy Requirements.
* Our pr is **earlier than** the  `containers/image`'s.
However, theirs are more popular and if we carry on ours, there may be compatibility issues.

_Originally posted by @Xynnn007 in https://github.com/confidential-containers/image-rs/issues/39#issuecomment-1186708165_

**Comment by arronwy** [comment]
Hi @sameo @fitzthum @jialez0 , we follow the signature verification policy file defined by [containers/images ](https://github.com/containers/image) at the beginning, and we introduce `scheme` filed to support different signature schemes like `cosign`, but we just found containers/image also added the `cosign` support and utilize the `type` field: https://github.com/containers/image/commit/64756915ba0e05baa52d1b911c401e05f540b3bf

Should we follow the `containers/image` format or continue our own definition?

**Comment by fitzthum** [comment]
Well my hunch would be to follow containers/image. We might have been first, but I think most people will care more about what they do. I do see how our version could be nicer, but honestly I don't know much about the `image-rs` code. We can ask people to take a look at this issue during the Thursday meeting and hopefully generate some discussion.

**Comment by Xynnn007** [comment]
> Well my hunch would be to follow containers/image. We might have been first, but I think most people will care more about what they do. I do see how our version could be nicer, but honestly I don't know much about the `image-rs` code. We can ask people to take a look at this issue during the Thursday meeting and hopefully generate some discussion.

Yes. I think we can flexibly change our format to avoid compatibility issues. Some fixes are introduced in this commit for docs
https://github.com/confidential-containers/image-rs/pull/39/commits/8476136e677715605d168be0e862edece5af2754. If ok, please close this issue and help to review the PR https://github.com/confidential-containers/image-rs/pull/39. 

And I'd like to carry on cosign support.

**Comment by sameo** [comment]
> Well my hunch would be to follow containers/image. We might have been first, but I think most people will care more about what they do. I do see how our version could be nicer, but honestly I don't know much about the `image-rs` code. We can ask people to take a look at this issue during the Thursday meeting and hopefully generate some discussion.

Same here, I think we should be in sync with the containers/image format.

**Comment by sameo** [comment]
> > Well my hunch would be to follow containers/image. We might have been first, but I think most people will care more about what they do. I do see how our version could be nicer, but honestly I don't know much about the `image-rs` code. We can ask people to take a look at this issue during the Thursday meeting and hopefully generate some discussion.
> 
> 
> 
> Yes, thanks. I think we can flexibly change our format to avoid compatibility issues. Some fixes are introduced in this commit for docs https://github.com/confidential-containers/image-rs/pull/39/commits/8476136e677715605d168be0e862edece5af2754
> 
> 
> 
> If ok, please close this issue and help to review the PR https://github.com/confidential-containers/image-rs/pull/39. 
> 

Could you please have that PR close that issue by including a Fixes # line in one of the commit?
