### ISSUE TITLE
Add integration test for signature verification with sample_kbc

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/image-rs#43]
Following on from the work in https://github.com/confidential-containers/attestation-agent/pull/69 we should be able to add a new integration test to integration.rs that covers using `sample_kbc` through the `attestation-agent` to provide the files/config needed to test signature verification. This should cover the positive and negative cases.
If it's helpful we can re-use the signed images and artefacts used in the 'unit test': in https://github.com/confidential-containers/image-rs/blob/main/src/image.rs#L251 - the test_data for this is in https://github.com/confidential-containers/image-rs/tree/main/test_data/simple-signing-scheme

This integration test would help provide the baseline to check that the get_resource endpoint feature in `sample_kbc` works and integrates with `image-rs`

## Acceptance Criteria

_**Scenario:** Pulling a non-signed image, from an 'unprotected registry' works_
**Given** I have image-rs configured with a policy.json, sigstore config, public GPG key and signature claim file valid for container registry `quay.io/kata-containers/confidential-containers`
**When** I call the `pull_image` method with a valid image URI from a different container registry repository that is not signed eg `quay.io/prometheus/busybox:latest`
**Then** The image-rs image pull operation succeeds.

_**Scenario:** Pulling a non-signed image, from a 'protected registry' is rejected_
**Given** I have image-rs configured with a policy.json, sigstore config, public GPG key and signature claim file valid for container registry `quay.io/kata-containers/confidential-containers`
**When** I call the `pull_image` method with a valid, unsigned image URI from the `quay.io/kata-containers/confidential-containers` container registry repository `quay.io/kata-containers/confidential-containers:unsigned`
**Then** The image-rs image pull operation fails
  **And** Hopefully there is an error message to explain what happened

_**Scenario:** Pulling a signed image, from a 'protected registry' succeeds_
**Given** I have image-rs configured with a policy.json, sigstore config, public GPG key and signature claim file valid for container registry `quay.io/kata-containers/confidential-containers`
**When** I call the `pull_image` method with a valid, signed, image URI that is signed from the `quay.io/kata-containers/confidential-containers` container registry repository `quay.io/kata-containers/confidential-containers:signed`
**Then** The image-rs image pull operation should succeed.

_**Scenario:** Pulling a signed image with mismatched key fails_
**Given** I have image-rs configured with a policy.json, sigstore config, public GPG key and signature claim file valid for container registry `quay.io/kata-containers/confidential-containers`
**When** I call the `pull_image` method with a valid image URI that is signed *with a different gpg key* from the `quay.io/kata-containers/confidential-containers` container registry repository `quay.io/kata-containers/confidential-containers:other_signed`
**Then** The image-rs image pull operation fails
  **And** Hopefully there is an error message to explain what happened

**Comment by Xynnn007** [comment]
Hi @stevenhorsman , I'd like to take this work. However, I'm confused about the term `unprotected registry` here. Two possible meaning here:
* This image's repository is included in the `security_policy.json`'s `transports/docker`
* This image's repository can be accessed only when we sign in it, i.e. using a `auth_info` containing a `password` and a `username`

I've read the first occurrence in [kata-containers](https://github.com/kata-containers/kata-containers/issues/2682) but am still confused.

**Comment by stevenhorsman** [comment]
Hi Ding, I'm sorry - 'protected registry' is a really bad name for it, so I understand your confusion. What I mean is a registry that has `transports/docker` in the policy.json (that isn't just `"type": "insecureAcceptAnything"`), not an authenticated registry. Hopefully that clarifies, and I think the same use cases from kata-containers have been copied to the image-rs unit tests, but I bit of documentation https://github.com/kata-containers/kata-containers/blob/CCv0/docs/how-to/how-to-build-and-test-ccv0.md#verifying-signed-images if that is any help?
Anything I can do to clarify/help - please let me know!

**Comment by Xynnn007** [comment]
@stevenhorsman Thank you very much! That does help a lot. :)
