### ISSUE TITLE
Support multiple public keys when verifying signatures

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/image-rs#50]
**Background**

As stated in https://github.com/confidential-containers/attestation-agent/issues/63, `image-rs` needs to support multiple public GPG keys.

Generally speaking, Simple signing (GPG key rings), cosign (ECDSA_P256 public keys) and other signing schemes may need more than one public key to verify images from different repositories, e.g., in [sample policy.json](https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md#a-reasonably-locked-down-system).

However, now public key used in simple signing is fixed in `/run/image-security/simple_signing/pubkey.gpg`. `Image-rs` will firstly check whether this key ring exists or not. If not, it will be retrieved from KBS via `GetResource` gRPC. We can not retrieve different public keys.

**TODO**

* Introduce a effective mechanism to support retrieving different public keys to verify different image signatures

**Comment by Xynnn007** [comment]
### Approaches

I think there may be three ways to handle this.

#### Way 1: Include `keyData` in `policy.json` instead of `keyPath` by default

As we know, current signing schemes (simple signing, and cosign under reviewing) has two field in the `policy.json`, s.t. `keyData` and `keyPath`. To avoid requesting for public keys, we can use the `keyData` instead of `keyPath` in `policy.json`. As image-rs will firstly check whether `policy.json` exists, and will request it from KBS if not. Together with the policies, the public key data will be retrieved. like

```json
{
    "default": [{"type": "reject"}], /* Reject anything not explicitly allowed */
    "transports": {
        "docker": {
            /* Allow installing images from a specific repository namespace, without cryptographic verification.
               This namespace includes images like openshift/hello-openshift and openshift/origin. */
            "docker.io/openshift": [{"type": "insecureAcceptAnything"}],
            /* Similarly, allow installing the “official” busybox images.  Note how the fully expanded
               form, with the explicit /library/, must be used. */
            "docker.io/library/busybox": [{"type": "insecureAcceptAnything"}],
            /* Allow installing images from all subdomains */
            "*.temporary-project.example.com": [{"type": "insecureAcceptAnything"}],
            /* A sigstore-signed repository */
            "hostname:5000/myns/sigstore-signed-with-full-references": [
                {
                    "type": "sigstoreSigned",
                    "keyData": "<BASE64-ENCODED-DATA>"
                }
            ],
            /* A sigstore-signed repository, accepts signatures by /usr/bin/cosign */
            "hostname:5000/myns/sigstore-signed-allows-malicious-tag-substitution": [
                {
                    "type": "sigstoreSigned",
                    "keyData": "<BASE64-ENCODED-DATA>"
                    "signedIdentity": {"type": "matchRepository"}
                }
            ]
            /* Other docker: images use the global default policy and are rejected */
        },
        "dir": {
            "": [{"type": "insecureAcceptAnything"}] /* Allow any images originating in local directories */
        },
        "atomic": {
            /* The common case: using a known key for a repository or set of repositories */
            "hostname:5000/myns/official": [
                {
                    "type": "signedBy",
                    "keyType": "GPGKeys",
                    "keyData": "<BASE64-ENCODED-DATA>"
                }
            ],
            /* A more complex example, for a repository which contains a mirror of a third-party product,
               which must be signed-off by local IT */
            "hostname:5000/vendor/product": [
                { /* Require the image to be signed by the original vendor, using the vendor's repository location. */
                    "type": "signedBy",
                    "keyType": "GPGKeys",
                    "keyData": "<BASE64-ENCODED-DATA>",
                    "signedIdentity": {
                        "type": "exactRepository",
                        "dockerRepository": "vendor-hostname/product/repository"
                    }
                },
                { /* Require the image to _also_ be signed by a local reviewer. */
                    "type": "signedBy",
                    "keyType": "GPGKeys",
                    "keyData": "<BASE64-ENCODED-DATA>"
                }
            ],
            /* A way to mirror many repositories from a single vendor */
            "private-mirror:5000/vendor-mirror": [
                { /* Require the image to be signed by the original vendor, using the vendor's repository location.
                     For example, private-mirror:5000/vendor-mirror/productA/image1:latest needs to be signed as
                     vendor.example/productA/image1:latest . */
                    "type": "signedBy",
                    "keyType": "GPGKeys",
                    "keyData": "<BASE64-ENCODED-DATA>",
                    "signedIdentity": {
                        "type": "remapIdentity",
                        "prefix": "private-mirror:5000/vendor-mirror",
                        "signedPrefix": "vendor.example.com"
                    }
                }
            ]
        }
    }
}
```

We can see in this way all pubkeys are given by data rather than path.

#### Way 2: Using optional field to include the repository of the image

[The optional field](https://github.com/confidential-containers/attestation-agent/blob/main/src/kbc_modules/mod.rs#L135) of `ResourceDescription` can bring extra information of the requested resource. Thus we can include the [scope field](https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md#supported-transports-and-their-scopes) in `policy.json` of the image to ask KBS for the concrete key. For example a `ResourceDescription`:
```json
{
    "name" : "GPG Keyring",
    "optional": {
        "scope": "example.com/busy-box",
    }
}
```
will match the policy in `policy.json`
```json
"example.com/busy-box": [
    {
        "type": "signedBy",
        "keyPath": "<Some-public-key>"
    }
]
```

This json indicates the GPG public keyring asked via `GetResource` gRPC is for `"example.com/busy-box"`.

#### Way 3: Define a new URI scheme `kbs://<resource-name>:<tag>`

We can define a new URI scheme, which can be used in `keyPath`. Because the URI of the `KBS` and the name of `KBC` is already given by the caller of image-rs (the parameter [`decrypt_config`](https://github.com/confidential-containers/image-rs/blob/main/src/image.rs#L118)), so we just need to involve the resource name and a tag in the new URI. Here the tag can specify the concrete resource, and the `resource name` here can be treated as a type (like `GPG Keyring`). For example, the example in Way 2 can be 

```json
"example.com/busy-box": [
    {
        "type": "signedBy",
        "keyPath": "kbs://gpg-keyring:112"
    }
]
```

This new URI is consumed in image-rs, and will be translated into a `ResourceDescription` and request it from the KBS as
```json
{
    "name" : "GPG Keyring",
    "optional": {
        "tag": "112",
    }
}
```
Will request for the GPG Keyring tagged by `112`. The mechanism is like a registry.

### Cons & Pros
|Way| Pros | Cons|
|---|---|---|
|Way 1| At most request from KBS once | Less flexibility |
|Way 2| Good mapping relationship and straightforward | If one specific public key is used to verify many different repositories, there may involve duplication of storage and configuration |
|Way 3| Straightforward, and compatible with other URI schemes | - |

Here, "compatible with other URI schemes" here means we can use different URI schemes in `keyPath` field, like
* `"keyPath": "/path/to-pubkey"`
* `"keyPath": "file:///path/to-pubkey"`
* `"keyPath": "https://example.com/public-key"`
* `"keyPath": "kbs://gpgkey-ring:1"`
* `"keyPath": "kbs://gpgkey-ring:1"`
* `"keyPath": "kms://example-kms/key-id"`
* ...

I prefer to Way 3. Do you have any suggestions?

**Comment by liudalibj** [comment]
Thanks @Xynnn007 for create this issues to support multiple public keys when verifying signatures.
Here are my comments:
- Way 1: this is a simple implement, no more change need be done in image-rs side, but we need end user use the `keyData` style in `policy.json` or need the KBS convert `keyPath` to `keyData` style when provide the `policy.json` to `image-rs`

- Way 2: I wonder that only use `scope` maybe not enough, we should include the `transport` field too, refer to [supported-transports-and-their-scopes](https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md#supported-transports-and-their-scopes)
For example a ResourceDescription:
```json
{
    "name" : "GPG Keyring",
    "optional": {
        "transport": "atomic", 
        "scope": "example.com/busy-box",
    }
}
```
And we should noticed that in some cases, multiple public keys will be used in one scope, the keys should be return in a  array with correct order by `get_resource` API, and `image-rs` must deal the response correctly.
eg. in [sample polic.json](https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md#a-reasonably-locked-down-system)
```
            "hostname:5000/vendor/product": [
                { /* Require the image to be signed by the original vendor, using the vendor's repository location. */
                    "type": "signedBy",
                    "keyType": "GPGKeys",
                    "keyPath": "/path/to/vendor-pubkey.gpg",
                    "signedIdentity": {
                        "type": "exactRepository",
                        "dockerRepository": "vendor-hostname/product/repository"
                    }
                },
                { /* Require the image to _also_ be signed by a local reviewer. */
                    "type": "signedBy",
                    "keyType": "GPGKeys",
                    "keyPath": "/path/to/reviewer-pubkey.gpg"
                }
            ],
```
the return array should be something:
```
[
  "content of /path/to/vendor-pubkey.gpg",
  "content of /path/to/reviewer-pubkey.gpg"
]
```
- Way 3. Define a new URI scheme `kbs://<resource-name>:<tag>` is a good way.
In the [sample polic.json](https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md#a-reasonably-locked-down-system) we can see there are many keys be used.
  - /path/to/sigstore-pubkey.pub
  - /path/to/official-pubkey.gpg
  - /path/to/vendor-pubkey.gpg
  - /path/to/reviewer-pubkey.gpg

So should we add the key name to the URI? 
For example, the example in Way 2 can be
```
"example.com/busy-box": [
    {
        "type": "signedBy",
        "keyPath": "kbs://gpg-keyring/vendor:112"
    }
]
```
This new URI is only consumed in image-rs and only used in KBS-involved scenarios. It will be translated into a ResourceDescription and request it from the KBS as
```
{
    "name" : "GPG Keyring",
    "optional": {
        "name": "vendor"
        "tag": "112",
    }
}
```
The KBS will manager all gpg keys, and return the correct GPG public key by given `key name` and `tag`. 
To reduce duplicate call about `get_resource` image-rs maybe need check whether the `kbs://gpg-keyring/vendor:112` be downloaded to local already.

I prefer to Way 3 too for long time goal, we can use Way 1 for dev/test purpose short time surely.

**Comment by Xynnn007** [comment]
> * Way 2: I wonder that only use `scope` maybe not enough, we should include the `transport` field too, refer to [supported-transports-and-their-scopes](https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md#supported-transports-and-their-scopes)
>   For example a ResourceDescription:

Yes, that's great. 

> So should we add the key name to the URI? For example, the example in Way 2 can be
> 
> ```
> "example.com/busy-box": [
>     {
>         "type": "signedBy",
>         "keyPath": "kbs://gpg-keyring/vendor:112"
>     }
> ]
> ```
> 
> This new URI is only consumed in image-rs and only used in KBS-involved scenarios. It will be translated into a ResourceDescription and request it from the KBS as
> 
> ```
> {
>     "name" : "GPG Keyring",
>     "optional": {
>         "name": "vendor"
>         "tag": "112",
>     }
> }
> ```
> 
> The KBS will manager all gpg keys, and return the correct GPG public key by given `key name` and `tag`. To reduce duplicate call about `get_resource` image-rs maybe need check whether the `kbs://gpg-keyring/vendor:112` be downloaded to local already.

Yes, I agree with you. Here it will be represented as `kbs://<resource-name>/<sub-type>:<tag>`, and it looks like an image registry very much. In this way, the resource management on the KBS side will be easy to implement with a HashMap-like data structure. 

> I prefer to Way 3 too for long time goal, we can use Way 1 for dev/test purpose short time surely.

Agreed.

**Comment by ariel-adam** [comment]
@Xynnn007 is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by Xynnn007** [comment]
For the way3, s.t. kbs URL.

This url is used inside image-rs, and will be translated into a `ResourceDescriptor`, which has a field `name` and a extra parameter hashmap `optional`. So we need a convenient kbs url format and a rule to map a `kbs://` url into a `ResourceDescriptor`. There may be different designs, two are as following:

#### Way 1

* KBS URL format: `kbs://<basic-directory>/<resource-name>:<tag>`
* Rule: a url `kbs://<basic-directory>/<resource-name>:<tag>` (which is the same as `kbs://<resource-description>/<sub-type>:<tag>`, but changed the field name) will be mapped into the following `ResourceDescriptor`
```json
{
    "name": "<resource-name>",
    "optional": {
        "directory": "<basic-directory>",
        "tag":"<tag>",
    }
}
```

For example, `kbs://user1/credential:quay.io` will be translated to
```json
{
    "name": "credential",
    "optional": {
        "directory": "user1",
        "tag":"quay.io",
    }
}
```
to request for a credential. And `kbs://policy:env1` to
```json
{
    "name": "policy",
    "optional": {
        "directory": "",
        "tag":"env1",
    }
}
```
to request for a `policy.json`.

#### Way 2

* KBS URL format: `kbs://<resource-name>?<key1>=<val1>`-like Query URL. All the `key`s and `val`s will be Percent-encoded
* Rule: a url  `kbs://<resource-name>?<key1>=<val1>&...<keyn>=<valn>` will be mapped into the following `ResourceDescriptor`
```json
{
    "name": "<resource-name>",
    "optional": {
        "<key1>": "<val1>",
        "<key2>": "<val2>",
        ...
        "<keyn>": "<valn>",
    }
}
```

For example, `kbs://credential?registry=quay.io` requests a credential of registry `quay.io`, will be translated into the `ResourceDescriptor`
```json
{
    "name": "credential",
    "optional": {
        "registry": "quay.io",
    }
}
```

And `kbs://publickey?type=cosign&keyid=2` will be translated into
```json
{
    "name": "publickey",
    "optional": {
        "type": "cosign",
        "keyid":"2",
    }
}
```

The first one has fixed fields in the `optional`, s.t. `directory` and `tag`, the second has more extensibility.
Still, the content of a `ResourceDescriptor` is finally processed by a KBC, especially our [CC-KBC](https://github.com/confidential-containers/attestation-agent/tree/main/src/kbc_modules/cc_kbc) under development.

Can anyone share some opinions upon this?

**Comment by liudalibj** [comment]
@Xynnn007 I like the Way 2 option, as it's more extensibility and easily to convert the kbs url to `ResourceDescriptor` request. And the optional fields need be processed by each KBC.
