### ISSUE TITLE
Support different signature schemes.

### ISSUE THREAD

**Issue by jialez0** [confidential-containers/image-rs#7]
As mentioned in #6 , There are multiple image signing and verification protocols/solutions available now, and there’s no standardization work for image signing yet. So in the image-rs of confidential containers, we should support different signature mechanisms with modular implementation.

In order to achieve this goal, we should first reconstruct the current signature verification function (#5 ) and modularize it to provide scalability for supporting more signature schemes. Specifically, the functions that need modularization include:

1. Getting signature: In different signature schemes, the storage and distribution methods of signature are different.
2. Parsing signature payload: Different signature schemes may use different signature payload formats.
3. Cryptography signature verification: Different signature schemes may use different signature algorithms.

After modularizing the above functions, we should add more signature schemes to support the verification of images signed by different schemes, such as:

1. Image signed with [Red Hat simple signing scheme](https://www.redhat.com/en/blog/container-image-signing).
2. Images signed with [cosign](https://github.com/sigstore/cosign) signature tool.
3. Image signed with [Alibaba cloud ACR image signing scheme](https://partners-intl.aliyun.com/help/en/doc-detail/159642.htm).
4. ETC.

**Comment by bodzhang** [comment]
One more signature scheme to consider - [Notary V2/Notation](https://github.com/notaryproject/notation)
