### ISSUE TITLE
Get rid of Sample KBC in integration test

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/image-rs#85]
#### Background
Now, for integration tests we have both Sample KBC and Offline-Fs-KBC. Both KBCs do not really access the KBS via network, and they are used to test the availability of secure channel between image-rs module and the Attestation-Agent.

#### What feature do we want to improve?
I suggest to abandon Sample KBC in image-rs for the following reasons:
* As mentioned, the availability of secure channel between image-rs module and the Attestation-Agent can also be covered by Offline-Fs-KBC. We might not need two to confirm.
* When new resources are changed, Sample KBC needs to recompile for the data is included in the code. However Offline-Fs-Kbc only needs to change the data file `/etc/aa-offline_fs_kbc-resources`, which is easy to handle.

#### Related issue
https://github.com/confidential-containers/community/issues/57

**Comment by Xynnn007** [comment]
I'm not sure whether it impacts Kata-CI that uses image-rs, could you share some views?
@stevenhorsman @arronwy

**Comment by arronwy** [comment]
AFAIK, kata CI don't use sample kbc, @stevenhorsman can help confirm.

**Comment by stevenhorsman** [comment]
Hey @Xynnn007 - Arron is correct - the Kata CI uses the offline_fs_kbc and I've been interested in merging the offline KBCs for a while, so this sounds great to me. Thanks!
