### ISSUE TITLE
attestation-agent version doesn't match the latest rats-tls

### ISSUE THREAD

**Issue by huliucheng1** [confidential-containers/image-rs#97]
https://github.com/confidential-containers/image-rs/blob/main/Cargo.toml#L20
https://github.com/confidential-containers/ocicrypt-rs/blob/main/Cargo.toml#L31

The latest rats-tls has fixed some bugs and the attestation-agent version specified in image-rs and ocicrypt-rs's Cargo.toml should be replaced to the latest one. 

Enclave-cc can't pass case tests using the old version of attestation-agent with latest rats-tls.

**Comment by arronwy** [comment]
Thanks @Xynnn007 , fixed now!
